releases:
  - name: passenger-api-graphql
    namespace: {{ env "NAMESPACE" | default "happyride" }}     
    chart: charts/passenger-api-graphql
    values:
      - image:
          tag: {{ requiredEnv "PASSENGER_API_GRAPHQL_VERSION" | quote }} 