repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql-passenger
    namespace: {{ env "NAMESPACE" | default "happyride" }} 
    chart: bitnami/postgresql
    version: 8.10.13   
    wait: false
    values:
      - ../postgresql-config.yaml
      - config.yaml
  - name: passenger-service
    namespace: {{ env "NAMESPACE" | default "happyride" }}     
    chart: charts/passenger-service
    values:
      - config.yaml
      - image:
          tag: {{ requiredEnv "PASSENGER_SERVICE_VERSION" | quote }} 
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"  