releases:
  - name: axon
    namespace: {{ env "NAMESPACE" | default "happyride" }}
    chart: charts/axon
    wait: false
    values:
      - resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
