spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: happyride
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:8433}/${DB_NAME:happyride-dispatch}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  redis:
    url: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
  flyway:
    schemas:
      - happyride
axon:
  axonserver:
    servers: ${AXON_HOST:localhost}:${AXON_PORT:8124}
  serializer:
    events: jackson
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
  zookeeper:
    connection:
      string: ${ZOOKEEPER_HOST:localhost}:${ZOOKEEPER_PORT:2181}
