repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql-address
    namespace: {{ env "NAMESPACE" | default "happyride" }} 
    chart: bitnami/postgresql
    version: 8.10.13   
    wait: false
    values:
      - ../postgresql-config.yaml
      - config.yaml
  - name: address-service-common
    namespace: {{ env "NAMESPACE" | default "happyride" }}     
    chart: charts/address-service-common   
  - name: address-service-{{ requiredEnv "DEPLOYMENT_TYPE" }}  
    namespace: {{ env "NAMESPACE" | default "happyride" }}     
    chart: charts/address-service
    values:
      - config.yaml
      - address-service-config.yaml
      - deploymentType: {{ requiredEnv "DEPLOYMENT_TYPE" | quote }}  
        appVersion: {{ requiredEnv "ADDRESS_SERVICE_VERSION" | quote }}   
        image:
          repository: {{ printf "%shappyride/happyride-address-service" (env "CONTAINER_REGISTRY" | default "" ) | quote }}  