server:
  port: 8505
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_HOST_IP:localhost}:8434/happyride-trip-validation
    username: postgres
    password: postgres
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:29092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181
app:
  blockedPassengers:
    - bad_passenger1
    - bad_passenger2