openapi: '3.0.3'
info:
  title: Trip service
  version: '1.0'
servers:
  - url: http://localhost:8501
tags:
  - name: trip
    description: Trip
paths:
  /:
    post:
      tags:
        - trip
      summary: Create a trip
      operationId: createTrip
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTripRequest"
        required: true      
      responses:
        '201':
          description: Successful
  /{tripId}:
    get:
      tags:
        - trip
      summary: Get a trip
      operationId: getTrip
      parameters:
        - name: tripId
          in: path
          description: Trip id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful  
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TripVO"
        '404':
          description: Trip not found
  /{tripId}/accept:
    post:
      tags:
        - trip
      summary: Accept a trip
      operationId: acceptTrip
      parameters:
        - name: tripId
          in: path
          description: Trip id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AcceptTripRequest"
        required: true
      responses:
        '200':
          description: Successful
components:
  schemas:
    CreateTripRequest:
      type: object
      properties:
        passengerId:
          type: string   
        startPos:
          $ref: "#/components/schemas/PositionVO"
        endPos:
          $ref: "#/components/schemas/PositionVO"
      required:
        - passengerId
        - startPos
        - endPos
    AcceptTripRequest:
        type: object
        properties:
          driverId:
            type: string
          posLng:
            type: number
            format: double
          posLat:
            type: number
            format: double
        required:
          - driverId
          - posLng
          - posLat
    TripVO:
      type: object
      properties:
        id: 
          type: string
        passengerId:
          type: string
        driverId:
          type: string
        startPos:
          $ref: "#/components/schemas/PositionVO"
        endPos:
          $ref: "#/components/schemas/PositionVO"
        state:
          type: string                     
    PositionVO:
      type: object
      properties:
        lng:
          type: number
          format: double
        lat:
          type: number
          format: double 
        addressId:
          type: string 
      required:
        - lng
        - lat     