repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: docker-registry
    namespace: {{ env "NAMESPACE" | default "happyride" }}
    chart: stable/docker-registry
    version: 1.9.4
    wait: true
    values:
      - service:
          type: NodePort
          nodePort: 30000
