apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: address-service
  labels:
    release: prom-o
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: address  
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: api
      interval: 10s
      path: "/actuator/prometheus"
      honorLabels: true  