apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-spring-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data: 
{{ (.Files.Glob "spring-config/**.yml").AsConfig | indent 2 }}
