package io.vividcode.happyride.tripservice.api;

public enum TripState {
  CREATED,
  REJECTED,
  CONFIRMED,
  DISPATCHED,
  ACCEPTED,
  FAILED,
  CANCELLED_BY_PASSENGER,
  CANCELLED_BY_DRIVER,
  CANCELLATION_PENDING,
  CANCELLED,
  CANCELLATION_REJECTED_BY_PASSENGER,
  CANCELLATION_REJECTED_BY_DRIVER,
  STARTED,
  FINISHED,
  PAYMENT_PENDING,
  PAID
}
