server:
  port: 8506
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: happyride
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_HOST_IP:localhost}:8436/happyride-trip-history
    username: postgres
    password: postgres
  flyway:
    schemas:
      - happyride

eventuate:
  database:
    schema: eventuate
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:29092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181